digitalocean:
  service: S3
  access_key_id: <%= ENV['DO_SPACES_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['DO_SPACES_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['DO_SPACES_REGION'] %>
  bucket: <%= ENV['DO_SPACES_BUCKET'] %>
  endpoint: <%= ENV['DO_SPACES_ENDPOINT'] %>
  force_path_style: true
