---
name: Bootstrap DogeOps

on:
    push:
        branches:
            - "production"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Deploy via DogeOps
              uses: WithAgency/dogeops-action@v1
              with:
                  api_url: ${{ vars.DOGEOPS_API_URL }}
                  api_key: ${{ secrets.DOGEOPS_API_KEY }}
